app_user:
    path: /user/dashboard
    defaults: { _controller: AppBundle:Default:userDashboard }
    
app_admin:
    path: /admin/dashboard
    defaults: { _controller: AppBundle:Default:adminDashboard }
